# Generated by Django 3.2.3 on 2021-06-04 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('watch_dog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=50)),
                ('report_version', models.CharField(max_length=10)),
                ('report_creatime', models.DateField()),
                ('report_status', models.BooleanField(default=False)),
                ('report_creater', models.CharField(max_length=20)),
                ('report_information', models.CharField(max_length=200)),
                ('report_root', models.CharField(max_length=100)),
                ('report_timeset', models.CharField(max_length=50)),
                ('report_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_dog_app.projectsinfo')),
            ],
            options={
                'db_table': 'wda_report_building',
            },
        ),
    ]
