# Generated by Django 3.2.3 on 2021-06-02 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('watch_dog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(max_length=50)),
                ('algorithm_version', models.CharField(max_length=10)),
                ('algorithm_creatime', models.DateField()),
                ('algorithm_status', models.BooleanField(default=False)),
                ('algorithm_creater', models.CharField(max_length=20)),
                ('algorithm_information', models.CharField(max_length=200)),
                ('algorithm_root', models.CharField(max_length=100)),
                ('algorithm_timeset', models.CharField(max_length=50)),
                ('algorithm_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_dog_app.projectsinfo')),
            ],
            options={
                'db_table': 'wda_algorithm_building',
            },
        ),
    ]
