# Generated by Django 3.2.3 on 2021-06-07 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('watch_dog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbscriptBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbscript_name', models.CharField(max_length=50)),
                ('dbscript_version', models.CharField(max_length=10)),
                ('dbscript_creatime', models.DateField()),
                ('dbscript_status', models.BooleanField(default=False)),
                ('dbscript_creater', models.CharField(max_length=20)),
                ('dbscript_information', models.CharField(max_length=200)),
                ('dbscript_root', models.CharField(max_length=100)),
                ('dbscript_timeset', models.CharField(max_length=50)),
                ('dbscript_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_dog_app.projectsinfo')),
            ],
            options={
                'db_table': 'wda_dbscript_building',
            },
        ),
    ]
